---
        - name: "centos7==installation"
          assert:
           success_msg: "proceed to installation "
           fail_msg: "this vm is not an centos 7 docker-distribution is not availible on centos8"
           that:
            ({{ansible_distribution_major_version}} == 7 )

        - name: " ==docker distribution"
          yum:
           name: [ python, firewalld, docker-distribution,python2-passlib, py-bcrypt]
           state: present

        - name: "create privatekey"
          openssl_privatekey:
           path: "{{path_prvkey}}"
           size: 4096

        - name: "create " 
          openssl_csr:
           path: "{{path_csr}}" 
           privatekey_path: "{{path_prvkey}}"
           country_name: BE
           organization_name: "{{name_org}}"
           common_name: "{{common_name_registry}}"       

        - name: " create selfsigned CA "
          openssl_certificate:
           provider: selfsigned
           privatekey_path: "{{path_prvkey}}"
           path: "{{path_cert}}"
           csr_path: "{{path_csr}}"
       
        - name: " create auth"
          htpasswd:
           path: "{{path_auth}}"
           create: yes
           state: present
           name: "{{name_auth}}"
           password: "{{passwd}}"
           crypt_scheme: bcrypt

        - name: "modi conf"
          copy:
           src: "{{config_file}}"
           dest: /etc/docker-distribution/registry/config.yml


        - name: "set firewall"
          firewalld:
           port: 5000/tcp
           permanent: true
           state: enabled
           #          notify: start firewall
           #          notify: start docker-distribution
