---
        - name: "centos7==installation"
          assert:
           success_msg: "proceed to installation "
           fail_msg: "this vm is not an centos 7 docker-distribution is not availible on centos8"
           that:
            ({{ansible_distribution_major_version}} == 7 )

        - name: " ==docker distribution"
          yum:
           name: [ python, firewalld, docker-distribution,python2-passlib, py-bcrypt]
           state: present

        - name: "create privatekey"
          openssl_privatekey:
           path: /etc/pki/tls/private/registryy.key
           size: 4096

        - name: "create " 
          openssl_csr:
           path: /etc/pki/tls/registryy.csr 
           privatekey_path: /etc/pki/tls/private/registryy.key
           country_name: BE
           organization_name: stage
           common_name: "{{common_name_registry}}"       

        - name: " create selfsigned CA "
          openssl_certificate:
           provider: selfsigned
           privatekey_path: /etc/pki/tls/private/registryy.key
           path: /etc/pki/tls/registryy.crt
           csr_path: /etc/pki/tls/registryy.csr 
       
        - name: " create auth"
          htpasswd:
           path: /etc/docker-distribution/dockerpasswd
           create: yes
           state: present
           name: "dock"
           password: "{{passwd}}"
           crypt_scheme: bcrypt

        - name: "modi conf"
          copy:
           src: /home/rayane/stage/config.yml
           dest: /etc/docker-distribution/registry/config.yml


        - name: "set firewall"
          firewalld:
           port: 5000/tcp
           permanent: true
           state: enabled
           #          notify: start firewall
           #          notify: start docker-distribution
