version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    tls:
        certificate: /etc/pki/tls/registryy.crt
        key: /etc/pki/tls/private/registryy.key
auth:
    htpasswd:
             path: /etc/docker-distribution/dockerpasswd
             realm: docker-distributions
                  
