---

     - name: copy file
       copy:
        src: kuber_firewall
        dest: /etc/firewalld/services/kubernetes_firewall.xml

     - name : "reload firewalld"
       service:
        name: firewalld
        state: reloaded

     - name: Manage  firewalld service
       firewalld:
        service: kubernetes_firewall
        permanent: yes
        immediate: yes
        state: enabled

     - name : "reload firewalld"
       service:
        name: firewalld
        state: reloaded


     - name: Copy the join command to server location
       copy: src=join-command dest=/tmp/join-command.sh mode=0777

     - name: Join the node to cluster
       command: sh /tmp/join-command.sh
