---

     - name: copy file
       copy:
        src: kuber_firewall
        dest: /etc/firewalld/services/kubernetes_firewall.xml

     - name : "reload firewalld"
       service:
        name: firewalld
        state: reloaded

     - name: set firewall
       command: firewall-cmd --permanent --add-service=kubernetes_firewall

     - name: Copy the join command to server location
       copy: src=join-command dest=/tmp/join-command.sh mode=0777

     - name: Join the node to cluster
       become_user: demo
       command: sh /tmp/join-command.sh
