---
           - name: validate partitions
             assert:
              success_msg: size(/var/lib/docker) > 1GB
              that:
               ( {{ espace_disk | int }} *(1024**3)) < (ansible_mounts | selectattr( "mount","eq","{{mount_on}}") | list)[0].size_available

           - name: "telecharger paquet necessaire"
             yum:
              name: [ "python3","firewalld","vim" ]

           - name: 'ajouter repository'
             yum_repository:
              description: "docker-ce-stable"
              name: docker-ce  
              baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
              gpgkey: "https://download.docker.com/linux/centos/gpg"

           - name: "telecharger paquet"
             yum:
              name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
              state: present





