---

           - name: 'ajouter repository'
             yum_repository:
              name: "Docker CE Stable - $baseacrh"
              description: "docker"
              baseurl: "https://download.docker.com/linux/centos/docker-ce.repo/7/$basearch/stable"
              gpgkey: "https://download.docker.com/linux/centos/gpg"

           - name: "telecharger paquet"
             yum:
              name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
              state: present

           - name: "telecharger paquet necessaire"
             yum:
              name: [ "python3","firewalld","vim" ]




