---

           - name: gather facts
             setup:


           - name: "validate partitions"    #verified if there's enough space on the disk
             assert:                           
              success_msg:  "{{directory_docker}} > {{espace_disk}}GB"
              fail_msg: "disk space insufisient"
              that:
               ( {{ espace_disk | int }} * (1024**3)) < (ansible_mounts | selectattr( "mount","eq",item) |map(attribute= "size_available") | list )[0] 
             with_items: "{{mount_point}}" 
                                        
                

           - name: "telecharger paquet necessaire"
             yum:
              name: [ "python3","firewalld","vim" ]  
              update_cache: yes

           - name: 'ajouter repository'
             yum_repository:                            
              description: "Docker Ce Stable - x86_64 "
              name: docker-ce-stable  
              baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
              gpgkey: "https://download.docker.com/linux/centos/gpg"
              gpgcheck: 1
              enabled: 1

           - name: "telecharger paquet"
             yum:
              name: https://download.docker.com/linux/centos/8/x86_64/stable/Packages/containerd.io-1.3.7-3.1.el8.x86_64.rpm
              state: present



              
