---

           - name: "validate partitions"    #verifie si il y a assez d'espace disponible disponible 
             assert:                        # ce module s'assure qu'une condition est remplis    
              success_msg:  "{{directory_docker}} > 1GB"
              fail_msg: "espace disponible insufisant"
              that:
               ( {{ espace_disk | int }} *(1024**3)) < (ansible_mounts | selectattr( "mount","eq",item) |map(attribute= "size_available") | list )[0] #affiche les facts relatifs au differents 
             with_items: "{{mount_on}}" # disk avec la commande select on filtre pour n'avoir que le
                                        #disk cible et ensuite on demande l'espace disponibl
                

           - name: "telecharger paquet necessaire"
             yum:
              name: [ "python3","firewalld","vim" ]  #installation des packet
              update_cache: yes

           - name: 'ajouter repository'
             yum_repository:                            
              description: "Docker Ce Stable - x86_64 "
              name: docker-ce-stable  
              baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
              gpgkey: "https://download.docker.com/linux/centos/gpg"
              gpgcheck: 1
              enabled: 1

           - name: "telecharger paquet"
             yum:
              name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
              state: present





