---
# tasks file for kubernetes-install-master

    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 
    
    - name: create .kube directory
      become: yes
      become_user: demo
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/centos/.kube/config
        remote_src: yes
        owner: demo

    - name: install Pod network
      become: yes
      become_user: demo
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml 
