---

           - name: "install docker"
             yum:
              name: ["docker-ce","docker-ce-cli",]
              state: present
             notify: start docker
              
           




