---

           
           - name: "create dir"
             file:
              path: "/etc/docker"
              state: directory
              mode: 0755


           - name: "creation daemon.json "     
             file:
              path: "/etc/docker/daemon.json"     
              state: touch                         

           - name: "change path "
             lineinfile:
              path: /etc/docker/daemon.json                  
              line: ' { "data-root" : "{{directory_docker}}", "exec-opts": ["native.cgroupdriver=systemd"], "log-driver": "json-file", "log-opts": {"max-size": "100m"}}'


           - name: install docker
             yum:
              name: [docker-ce, docker-ce-cli]
              state: present
              
           - name: reload daemon
             systemd:
              daemon_reload: yes
           
           - name: start docker
             service:
              name: docker 
              state: started
              enabled: yes
            



              
