---

           
           - name: "create dir"
             file:
              path: "/etc/docker"
              state: directory
              mode: 0755


           - name: "creation daemon.json "     
             file:
              path: "/etc/docker/daemon.json"
              state: touch                         #on cree le fichier

           - name: "change path "
             lineinfile:
              path: /etc/docker/daemon.json                    #on modifie le document en y inserant
              line: ' { "data-root" : "{{directory_docker}}" }' # la nouvelle directory


           - name: install docker
             yum:
              name: [docker-ce, docker-ce-cli]
              state: present
             notify: stop docker
             notify: reload daemon
             notify: start docker

