---

           
           - name: "create dir"
             file:
              path: "/etc/docker"
              state: directory
              mode: 0755


           - name: "creation daemon.json "     
             file:
              path: "/etc/docker/daemon.json"      # on donne le path
              state: touch                         #on cree le fichier

           - name: "change path "
             lineinfile:
              path: /etc/docker/daemon.json                    #on modifie le document en y inserant
              line: ' { "data-root" : "{{directory_docker}}" }' # la nouvelle directory


           - name: install docker
             yum:
              name: [docker-ce, docker-ce-cli]
              state: present
              
           - name: reload daemon
             systemd:
              daemon_reload: yes
           
           - name: start docker
             service:
              name: docker 
              state: started
              enabled: yes
            



              
