---

      - name: " hosts"
        lineinfile:
         path: /etc/hosts
         line: '{{ip_registry}}:5000 docker-distributions'
        when: "{{ dns }}"
         
      - name: Create a directory 
        file:
         path: '/etc/docker/certs.d/docker-distributions:5000'
         state: directory
         mode: '0755'
         
      - name: copy file
        copy:
         src: registry.crt
         dest: '/etc/docker/certs.d/docker-distributions:5000/registry.crt '
