---
# handlers file for preparation---

        - name : "reload firewalld"
          service:
            name: firewalld
            state: reloaded

        - name: "start docker"
          service:
           name: docker 
           state: started
       
        - name: "stop docker"
          service:
           name: docker
           state: stopped

        - name: "reload daemon"
          systemd:
           daemond_reload: yes
           

        - name: "start firewalld"
          service:
           name: firewalld
           state: started
